print("🎸 Welcome to Chord Explorer!")
print("Discover notes and chord vibes.\n")

chord = input("Enter a chord: ")

chords = {
    "C": "C Major",
    "c": "C Major",
    "CM": "C Major",
    "cM": "C Major",
    "C M": "C Major",
    "c M": "C Major",
    "CMaj": "C Major",
    "cMaj": "C Major",
    "Cmaj": "C Major",
    "cmaj": "C Major",
    "C Maj": "C Major",
    "c Maj": "C Major",
    "C maj": "C Major",
    "c maj": "C Major",
    "CMajor": "C Major",
    "cMajor": "C Major",
    "Cmajor": "C Major",
    "cmajor": "C Major",
    "C Major": "C Major",
    "c Major": "C Major",
    "C major": "C Major",
    "c major": "C Major",
    "Cm": "C Minor",
    "cm": "C Minor",
    "C m": "C Minor",
    "c m": "C Minor",
    "CMin": "C Minor",
    "cMin": "C Minor",
    "Cmin": "C Minor",
    "cmin": "C Minor",
    "C Min": "C Minor",
    "c Min": "C Minor",
    "C min": "C Minor",
    "c min": "C Minor",
    "CMinor": "C Minor",
    "cMinor": "C Minor",
    "Cminor": "C Minor",
    "cminor": "C Minor",
    "C Minor": "C Minor",
    "c Minor": "C Minor",
    "C minor": "C Minor",
    "c minor": "C Minor",
    "C7": "C 7",
    "c7": "C 7",
    "C 7": "C 7",
    "c 7": "C 7",
    "C#": "C# Major",
    "c#": "C# Major",
    "C#M": "C# Major",
    "c#M": "C# Major",
    "C# M": "C# Major",
    "c# M": "C# Major",
    "C#Maj": "C# Major",
    "c#Maj": "C# Major",
    "C#maj": "C# Major",
    "c#maj": "C# Major",
    "C# Maj": "C# Major",
    "c# Maj": "C# Major",
    "C# maj": "C# Major",
    "c# maj": "C# Major",
    "C#Major": "C# Major",
    "c#Major": "C# Major",
    "C#major": "C# Major",
    "c#major": "C# Major",
    "C# Major": "C# Major",
    "c# Major": "C# Major",
    "C# major": "C# Major",
    "c# major": "C# Major",
    "C#m": "C# Minor",
    "c#m": "C# Minor",
    "C# m": "C# Minor",
    "c# m": "C# Minor",
    "C#Min": "C# Minor",
    "c#Min": "C# Minor",
    "C#min": "C# Minor",
    "c#min": "C# Minor",
    "C# Min": "C# Minor",
    "c# Min": "C# Minor",
    "C# min": "C# Minor",
    "c# min": "C# Minor",
    "C#Minor": "C# Minor",
    "c#Minor": "C# Minor",
    "C#minor": "C# Minor",
    "c#minor": "C# Minor",
    "C# Minor": "C# Minor",
    "c# Minor": "C# Minor",
    "C# minor": "C# Minor",
    "c# minor": "C# Minor",
    "C#7": "C# 7",
    "c#7": "C# 7",
    "C# 7": "C# 7",
    "c# 7": "C# 7",
    "D": "D Major",
    "d": "D Major",
    "DM": "D Major",
    "dM": "D Major",
    "D M": "D Major",
    "d M": "D Major",
    "DMaj": "D Major",
    "dMaj": "D Major",
    "Dmaj": "D Major",
    "dmaj": "D Major",
    "D Maj": "D Major",
    "d Maj": "D Major",
    "D maj": "D Major",
    "d maj": "D Major",
    "DMajor": "D Major",
    "dMajor": "D Major",
    "Dmajor": "D Major",
    "dmajor": "D Major",
    "D Major": "D Major",
    "d Major": "D Major",
    "D major": "D Major",
    "d major": "D Major",
    "Dm": "D Minor",
    "dm": "D Minor",
    "D m": "D Minor",
    "d m": "D Minor",
    "DMin": "D Minor",
    "dMin": "D Minor",
    "Dmin": "D Minor",
    "dmin": "D Minor",
    "D Min": "D Minor",
    "d Min": "D Minor",
    "D min": "D Minor",
    "d min": "D Minor",
    "DMinor": "D Minor",
    "dMinor": "D Minor",
    "Dminor": "D Minor",
    "dminor": "D Minor",
    "D Minor": "D Minor",
    "d Minor": "D Minor",
    "D minor": "D Minor",
    "d minor": "D Minor",
    "D7": "D 7",
    "d7": "D 7",
    "D 7": "D 7",
    "d 7": "D 7",
    "D#": "D# Major",
    "d#": "D# Major",
    "D#M": "D# Major",
    "d#M": "D# Major",
    "D# M": "D# Major",
    "d# M": "D# Major",
    "D#Maj": "D# Major",
    "d#Maj": "D# Major",
    "D#maj": "D# Major",
    "d#maj": "D# Major",
    "D# Maj": "D# Major",
    "d# Maj": "D# Major",
    "D# maj": "D# Major",
    "d# maj": "D# Major",
    "D#Major": "D# Major",
    "d#Major": "D# Major",
    "D#major": "D# Major",
    "d#major": "D# Major",
    "D# Major": "D# Major",
    "d# Major": "D# Major",
    "D# major": "D# Major",
    "d# major": "D# Major",
    "D#m": "D# Minor",
    "d#m": "D# Minor",
    "D# m": "D# Minor",
    "d# m": "D# Minor",
    "D#Min": "D# Minor",
    "d#Min": "D# Minor",
    "D#min": "D# Minor",
    "d#min": "D# Minor",
    "D# Min": "D# Minor",
    "d# Min": "D# Minor",
    "D# min": "D# Minor",
    "d# min": "D# Minor",
    "D#Minor": "D# Minor",
    "d#Minor": "D# Minor",
    "D#minor": "D# Minor",
    "d#minor": "D# Minor",
    "D# Minor": "D# Minor",
    "d# Minor": "D# Minor",
    "D# minor": "D# Minor",
    "d# minor": "D# Minor",
    "D#7": "D# 7",
    "d#7": "D# 7",
    "D# 7": "D# 7",
    "d# 7": "D# 7",
    "E": "E Major",
    "e": "E Major",
    "EM": "E Major",
    "eM": "E Major",
    "E M": "E Major",
    "e M": "E Major",
    "EMaj": "E Major",
    "eMaj": "E Major",
    "Emaj": "E Major",
    "emaj": "E Major",
    "E Maj": "E Major",
    "e Maj": "E Major",
    "E maj": "E Major",
    "e maj": "E Major",
    "EMajor": "E Major",
    "eMajor": "E Major",
    "Emajor": "E Major",
    "emajor": "E Major",
    "E Major": "E Major",
    "e Major": "E Major",
    "E major": "E Major",
    "e major": "E Major",
    "Em": "E Minor",
    "em": "E Minor",
    "E m": "E Minor",
    "e m": "E Minor",
    "EMin": "E Minor",
    "eMin": "E Minor",
    "Emin": "E Minor",
    "emin": "E Minor",
    "E Min": "E Minor",
    "e Min": "E Minor",
    "E min": "E Minor",
    "e min": "E Minor",
    "EMinor": "E Minor",
    "eMinor": "E Minor",
    "Eminor": "E Minor",
    "eminor": "E Minor",
    "E Minor": "E Minor",
    "e Minor": "E Minor",
    "E minor": "E Minor",
    "e minor": "E Minor",
    "E7": "E 7",
    "e7": "E 7",
    "E 7": "E 7",
    "e 7": "E 7",
    "F": "F Major",
    "f": "F Major",
    "FM": "F Major",
    "fM": "F Major",
    "F M": "F Major",
    "f M": "F Major",
    "FMaj": "F Major",
    "fMaj": "F Major",
    "Fmaj": "F Major",
    "fmaj": "F Major",
    "F Maj": "F Major",
    "f Maj": "F Major",
    "F maj": "F Major",
    "f maj": "F Major",
    "FMajor": "F Major",
    "fMajor": "F Major",
    "Fmajor": "F Major",
    "fmajor": "F Major",
    "F Major": "F Major",
    "f Major": "F Major",
    "F major": "F Major",
    "f major": "F Major",
    "Fm": "F Minor",
    "fm": "F Minor",
    "F m": "F Minor",
    "f m": "F Minor",
    "FMin": "F Minor",
    "fMin": "F Minor",
    "Fmin": "F Minor",
    "fmin": "F Minor",
    "F Min": "F Minor",
    "f Min": "F Minor",
    "F min": "F Minor",
    "f min": "F Minor",
    "FMinor": "F Minor",
    "fMinor": "F Minor",
    "Fminor": "F Minor",
    "fminor": "F Minor",
    "F Minor": "F Minor",
    "f Minor": "F Minor",
    "F minor": "F Minor",
    "f minor": "F Minor",
    "F7": "F 7",
    "f7": "F 7",
    "F 7": "F 7",
    "f 7": "F 7",
    "F#": "F# Major",
    "f#": "F# Major",
    "F#M": "F# Major",
    "f#M": "F# Major",
    "F# M": "F# Major",
    "f# M": "F# Major",
    "F#Maj": "F# Major",
    "f#Maj": "F# Major",
    "F#maj": "F# Major",
    "f#maj": "F# Major",
    "F# Maj": "F# Major",
    "f# Maj": "F# Major",
    "F# maj": "F# Major",
    "f# maj": "F# Major",
    "F#Major": "F# Major",
    "f#Major": "F# Major",
    "F#major": "F# Major",
    "f#major": "F# Major",
    "F# Major": "F# Major",
    "f# Major": "F# Major",
    "F# major": "F# Major",
    "f# major": "F# Major",
    "F#m": "F# Minor",
    "f#m": "F# Minor",
    "F# m": "F# Minor",
    "f# m": "F# Minor",
    "F#Min": "F# Minor",
    "f#Min": "F# Minor",
    "F#min": "F# Minor",
    "f#min": "F# Minor",
    "F# Min": "F# Minor",
    "f# Min": "F# Minor",
    "F# min": "F# Minor",
    "f# min": "F# Minor",
    "F#Minor": "F# Minor",
    "f#Minor": "F# Minor",
    "F#minor": "F# Minor",
    "f#minor": "F# Minor",
    "F# Minor": "F# Minor",
    "f# Minor": "F# Minor",
    "F# minor": "F# Minor",
    "f# minor": "F# Minor",
    "F#7": "F# 7",
    "f#7": "F# 7",
    "F# 7": "F# 7",
    "f# 7": "F# 7",
    "G": "G Major",
    "g": "G Major",
    "GM": "G Major",
    "gM": "G Major",
    "G M": "G Major",
    "g M": "G Major",
    "GMaj": "G Major",
    "gMaj": "G Major",
    "Gmaj": "G Major",
    "gmaj": "G Major",
    "G Maj": "G Major",
    "g Maj": "G Major",
    "G maj": "G Major",
    "g maj": "G Major",
    "GMajor": "G Major",
    "gMajor": "G Major",
    "Gmajor": "G Major",
    "gmajor": "G Major",
    "G Major": "G Major",
    "g Major": "G Major",
    "G major": "G Major",
    "g major": "G Major",
    "Gm": "G Minor",
    "gm": "G Minor",
    "G m": "G Minor",
    "g m": "G Minor",
    "GMin": "G Minor",
    "gMin": "G Minor",
    "Gmin": "G Minor",
    "gmin": "G Minor",
    "G Min": "G Minor",
    "g Min": "G Minor",
    "G min": "G Minor",
    "g min": "G Minor",
    "GMinor": "G Minor",
    "gMinor": "G Minor",
    "Gminor": "G Minor",
    "gminor": "G Minor",
    "G Minor": "G Minor",
    "g Minor": "G Minor",
    "G minor": "G Minor",
    "g minor": "G Minor",
    "G7": "G 7",
    "g7": "G 7",
    "G 7": "G 7",
    "g 7": "G 7",
    "G#": "G# Major",
    "g#": "G# Major",
    "G#M": "G# Major",
    "g#M": "G# Major",
    "G# M": "G# Major",
    "g# M": "G# Major",
    "G#Maj": "G# Major",
    "g#Maj": "G# Major",
    "G#maj": "G# Major",
    "g#maj": "G# Major",
    "G# Maj": "G# Major",
    "g# Maj": "G# Major",
    "G# maj": "G# Major",
    "g# maj": "G# Major",
    "G#Major": "G# Major",
    "g#Major": "G# Major",
    "G#major": "G# Major",
    "g#major": "G# Major",
    "G# Major": "G# Major",
    "g# Major": "G# Major",
    "G# major": "G# Major",
    "g# major": "G# Major",
    "G#m": "G# Minor",
    "g#m": "G# Minor",
    "G# m": "G# Minor",
    "g# m": "G# Minor",
    "G#Min": "G# Minor",
    "g#Min": "G# Minor",
    "G#min": "G# Minor",
    "g#min": "G# Minor",
    "G# Min": "G# Minor",
    "g# Min": "G# Minor",
    "G# min": "G# Minor",
    "g# min": "G# Minor",
    "G#Minor": "G# Minor",
    "g#Minor": "G# Minor",
    "G#minor": "G# Minor",
    "g#minor": "G# Minor",
    "G# Minor": "G# Minor",
    "g# Minor": "G# Minor",
    "G# minor": "G# Minor",
    "g# minor": "G# Minor",
    "G#7": "G# 7",
    "g#7": "G# 7",
    "G# 7": "G# 7",
    "g# 7": "G# 7",
    "A": "A Major",
    "a": "A Major",
    "AM": "A Major",
    "aM": "A Major",
    "A M": "A Major",
    "a M": "A Major",
    "AMaj": "A Major",
    "aMaj": "A Major",
    "Amaj": "A Major",
    "amaj": "A Major",
    "A Maj": "A Major",
    "a Maj": "A Major",
    "A maj": "A Major",
    "a maj": "A Major",
    "AMajor": "A Major",
    "aMajor": "A Major",
    "Amajor": "A Major",
    "amajor": "A Major",
    "A Major": "A Major",
    "a Major": "A Major",
    "A major": "A Major",
    "a major": "A Major",
    "Am": "A Minor",
    "am": "A Minor",
    "A m": "A Minor",
    "a m": "A Minor",
    "AMin": "A Minor",
    "aMin": "A Minor",
    "Amin": "A Minor",
    "amin": "A Minor",
    "A Min": "A Minor",
    "a Min": "A Minor",
    "A min": "A Minor",
    "a min": "A Minor",
    "AMinor": "A Minor",
    "aMinor": "A Minor",
    "Aminor": "A Minor",
    "aminor": "A Minor",
    "A Minor": "A Minor",
    "a Minor": "A Minor",
    "A minor": "A Minor",
    "a minor": "A Minor",
    "A7": "A 7",
    "a7": "A 7",
    "A 7": "A 7",
    "a 7": "A 7",
    "A#": "A# Major",
    "a#": "A# Major",
    "A#M": "A# Major",
    "a#M": "A# Major",
    "A# M": "A# Major",
    "a# M": "A# Major",
    "A#Maj": "A# Major",
    "a#Maj": "A# Major",
    "A#maj": "A# Major",
    "a#maj": "A# Major",
    "A# Maj": "A# Major",
    "a# Maj": "A# Major",
    "A# maj": "A# Major",
    "a# maj": "A# Major",
    "A#Major": "A# Major",
    "a#Major": "A# Major",
    "A#major": "A# Major",
    "a#major": "A# Major",
    "A# Major": "A# Major",
    "a# Major": "A# Major",
    "A# major": "A# Major",
    "a# major": "A# Major",
    "A#m": "A# Minor",
    "a#m": "A# Minor",
    "A# m": "A# Minor",
    "a# m": "A# Minor",
    "A#Min": "A# Minor",
    "a#Min": "A# Minor",
    "A#min": "A# Minor",
    "a#min": "A# Minor",
    "A# Min": "A# Minor",
    "a# Min": "A# Minor",
    "A# min": "A# Minor",
    "a# min": "A# Minor",
    "A#Minor": "A# Minor",
    "a#Minor": "A# Minor",
    "A#minor": "A# Minor",
    "a#minor": "A# Minor",
    "A# Minor": "A# Minor",
    "a# Minor": "A# Minor",
    "A# minor": "A# Minor",
    "a# minor": "A# Minor",
    "A#7": "A# 7",
    "a#7": "A# 7",
    "A# 7": "A# 7",
    "a# 7": "A# 7",
    "B": "B Major",
    "b": "B Major",
    "BM": "B Major",
    "bM": "B Major",
    "B M": "B Major",
    "b M": "B Major",
    "BMaj": "B Major",
    "bMaj": "B Major",
    "Bmaj": "B Major",
    "bmaj": "B Major",
    "B Maj": "B Major",
    "b Maj": "B Major",
    "B maj": "B Major",
    "b maj": "B Major",
    "BMajor": "B Major",
    "bMajor": "B Major",
    "Bmajor": "B Major",
    "bmajor": "B Major",
    "B Major": "B Major",
    "b Major": "B Major",
    "B major": "B Major",
    "b major": "B Major",
    "Bm": "B Minor",
    "bm": "B Minor",
    "B m": "B Minor",
    "b m": "B Minor",
    "BMin": "B Minor",
    "bMin": "B Minor",
    "Bmin": "B Minor",
    "bmin": "B Minor",
    "B Min": "B Minor",
    "b Min": "B Minor",
    "B min": "B Minor",
    "b min": "B Minor",
    "BMinor": "B Minor",
    "bMinor": "B Minor",
    "Bminor": "B Minor",
    "bminor": "B Minor",
    "B Minor": "B Minor",
    "b Minor": "B Minor",
    "B minor": "B Minor",
    "b minor": "B Minor",
    "B7": "B 7",
    "b7": "B 7",
    "B 7": "B 7",
    "b 7": "B 7"
}

chord_notes = {
    "C Major": "C, E, G",
    "C Minor": "C, Eb, G",
    "C 7": "C, E, G, Bb",
    "C# Major": "C#, F, G#",
    "C# Minor": "C#, E, G#",
    "C# 7": "C#, F, G#, B",
    "D Major": "D, F#, A",
    "D Minor": "D, F, A",
    "D 7": "D, F#, A, C",
    "D# Major": "D#, G, A#",
    "D# Minor": "D#, F#, A#",
    "D# 7": "D#, G, A#, C#",
    "E Major": "E, G#, B",
    "E Minor": "E, G, B",
    "E 7": "E, G#, B, D",
    "F Major": "F, A, C",
    "F Minor": "F, Ab, C",
    "F 7": "F, A, C, Eb",
    "F# Major": "F#, A#, C#",
    "F# Minor": "F#, A, C#",
    "F# 7": "F#, A#, C#, E",
    "G Major": "G, B, D",
    "G Minor": "G, Bb, D",
    "G 7": "G, B, D, F",
    "G# Major": "G#, C, D#",
    "G# Minor": "G#, B, D#",
    "G# 7": "G#, C, D#, F#",
    "A Major": "A, C#, E",
    "A Minor": "A, C, E",
    "A 7": "A, C#, E, G",
    "A# Major": "A#, D, F",
    "A# Minor": "A#, C#, F",
    "A# 7": "A#, D, F, G#",
    "B Major": "B, D#, F#",
    "B Minor": "B, D, F#",
    "B 7": "B, D#, F#, A"
}

chord_progressions = {
    "🔆  Bright": [
        ["C", "F", "G", "C"],
        ["G", "C", "D", "G"],
        ["A", "D", "E", "A"],
        ["D", "G", "A", "D"],
        ["F", "C", "G", "F"],
        ["C", "G", "Am", "F"],
        ["G", "D", "Em", "C"]
    ],
    "🥀  Sad": [
        ["Am", "Em", "Dm", "Am"],
        ["Dm", "Gm", "Am", "Dm"],
        ["Em", "Bm", "C", "Em"],
        ["Cm", "Gm", "Fm", "Cm"],
        ["Fm", "Cm", "D#", "Fm"],
        ["Am", "Dm", "E7", "Am"],
        ["Em", "Am", "Bm", "Em"]
    ],
    "⁉️  Suspenseful": [
        ["Cm", "G#", "F", "Cm"],
        ["D#m", "A#", "F#", "D#m"],
        ["Fm", "C#", "G#", "Fm"],
        ["Gm", "D#", "A#", "Gm"],
        ["C#m", "G#", "F#", "C#m"],
        ["Am", "F", "E7", "Am"]
    ],
    "☁️  Dreamy": [
        ["F", "G", "Am", "F"],
        ["C", "Em", "F", "G"],
        ["Dm", "G", "C", "Am"],
        ["Am", "F", "C", "G"],
        ["C", "F", "Dm", "G"],
        ["Em", "Am", "F", "G"],
        ["F", "Dm", "G", "C"]
    ],
    "💞  Romantic": [
        ["C", "Am", "F", "G"],
        ["G", "Em", "C", "D"],
        ["F", "Dm", "Gm", "C"],
        ["Am", "F", "C", "G"],
        ["Dm", "G", "C", "Am"],
        ["C", "G", "Am", "Em"],
        ["F", "C", "Dm", "G"]
    ],
    "💢  Raw & Aggressive": [
        ["E", "G", "A", "B"],
        ["F#", "B", "C#", "F#"],
        ["G#", "D#", "A#", "G#"],
        ["C", "G", "F", "C"],
        ["D", "A", "G", "D"],
        ["A", "E", "D", "A"],
        ["B", "F#", "E", "B"]
    ],
    "‼️  Dramatic": [
        ["Cm", "G", "A#", "Fm"],
        ["D#m", "A#", "C#", "G#"],
        ["Fm", "C", "D#", "G#"],
        ["Am", "F", "G", "Em"],
        ["Em", "C", "D", "Bm"],
        ["Gm", "D#", "A#", "F"],
        ["C#m", "A", "B", "E"]
    ]
}

if chord in chords:
    full_name = chords[chord]
    notes = chord_notes.get(full_name, "Unknown notes")
    print(f"\nYour chord: {full_name} 🎶")
    print(f"Notes in {full_name}: {notes}\n")

    full_to_short = {
        "C Major": "C",
        "C Minor": "Cm",
        "C 7": "C7",
        "C# Major": "C#",
        "C# Minor": "C#m",
        "C# 7": "C#7",
        "D Major": "D",
        "D Minor": "Dm",
        "D 7": "D7",
        "D# Major": "D#",
        "D# Minor": "D#m",
        "D# 7": "D#7",
        "E Major": "E",
        "E Minor": "Em",
        "E 7": "E7",
        "F Major": "F",
        "F Minor": "Fm",
        "F 7": "F7",
        "F# Major": "F#",
        "F# Minor": "F#m",
        "F# 7": "F#7",
        "G Major": "G",
        "G Minor": "Gm",
        "G 7": "G7",
        "G# Major": "G#",
        "G# Minor": "G#m",
        "G# 7": "G#7",
        "A Major": "A",
        "A Minor": "Am",
        "A 7": "A7",
        "A# Major": "A#",
        "A# Minor": "A#m",
        "A# 7": "A#7",
        "B Major": "B",
        "B Minor": "Bm",
        "B 7": "B7"
    }

    chord_symbol = full_to_short.get(full_name, full_name)

    found = False
    for emotion, progressions_list in chord_progressions.items():
        filtered = [progression for progression in progressions_list if chord_symbol in progression]
        if filtered:
            found = True
            print(f"{emotion} Progressions:")
            for progression in filtered:
                print(" - " + " - ".join(progression))
            print()

    if not found:
        print("Sorry, couldn't find a progression with that chord. 😅")
else:
    print("\nSorry, I don't know that chord yet. 😅")
